### ISSUE TITLE
Todoist Integration is broken broken

### ISSUE THREAD

**Issue by esalexreyes** [clockify/browser-extension#235]
It seems that Todoist updated their UI again, and the integration is broekn. At least on my end, the Clockify extension is not adding the button to track to the side of the task.

It's simple to replicate, just install the extension and add Todoist to the list of active integrations. Then going to your Todoist account, you will see that the clockify button never appears. The JS Console shows this error:

`Uncaught TypeError: Cannot read properties of null (reading 'textContent')
    at todoist.js:1:1075
    at Object.renderTo (clockifyButton.js:1:1035)
    at MutationObserver.callback (clockifyButton.js:1:1246)
    at e (clockifyDebounce.js:1:107)`

**Comment by cvbrian** [comment]
I'm running into this too.

**Comment by 7saraK** [comment]
Thank you both for reporting this. 

Please note that this has been already forwarded to the team, and as soon as the fix is live, I will update you here. 

In the meantime, if you have any other questions feel free to ask me. 

Kind Regards,

**Comment by 7saraK** [comment]
Hi both, @esalexreyes and @cvbrian, I just wanted to let you know that the new version of the extension is live. The fix for the Todoist is released with it. Please try it out and let me know here is there are any issues with the new version. Thank you for you patience on this matter! Cheers.

**Comment by kergma-lw** [comment]
Still not work...

**Comment by 7saraK** [comment]
Hi @kergma-lw, could you please uninstall the extension > clear the browser's cache and cookies, and install the extension again? Please let me know if that helped.

**Comment by kergma-lw** [comment]
I dd all these things. Not helped.

**Comment by kergma-lw** [comment]
```
The connection to https://push.rollout.io/sse/5d5a503b2385ac15e39b6051 was interrupted while the page was loading. vendor~add~app~authentication~electron-login~2a42e354.642dda3285822caa6872f1bf4d808304.js:10:59373
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). contentscript.js:1:157504
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”). today
Checker for https://todoist.com/app/today request refresh checker.js:23:17
TypeError: $(...) is null4 todoist.js:1:1038
    <anonymous> moz-extension://52ae6822-77f3-4191-bd00-65210bef3d60/integrations/todoist.js:1
    renderTo moz-extension://52ae6822-77f3-4191-bd00-65210bef3d60/popupDlg/clockifyButton.js:1
    callback moz-extension://52ae6822-77f3-4191-bd00-65210bef3d60/popupDlg/clockifyButton.js:1
    c moz-extension://52ae6822-77f3-4191-bd00-65210bef3d60/popupDlg/clockifyDebounce.js:1
    (Async: setTimeout handler)
    clockifyDebounce moz-extension://52ae6822-77f3-4191-bd00-65210bef3d60/popupDlg/clockifyDebounce.js:1
    (Async: MutationCallback)
    render moz-extension://52ae6822-77f3-4191-bd00-65210bef3d60/popupDlg/clockifyButton.js:1
    <anonymous> moz-extension://52ae6822-77f3-4191-bd00-65210bef3d60/integrations/todoist.js:1
```

**Comment by 7saraK** [comment]
Thank you for confirming this. 

Please note that earlier today we released the newest extension version (v2.9.3). Can you please confirm do you experience the same issue with this version? 
If yes, which browser do you use, and what is the version of your browser?

**Comment by kergma-lw** [comment]
Still not work. I did:

- uninstall clockify extension;
- restart browser;
- install clockify extension;
- restart browser;
- login clockify extension to clockify.com;
- unlogin todoist com;
- login todoist.com;
- clear browser cache for todoist.com.

**Comment by kergma-lw** [comment]
```

Checker for https://todoist.com/app/today request refresh checker.js:23:17
TypeError: $(...) is nulltodoist.js:1:1038
    <anonymous> moz-extension://c14f2050-21b4-4ea1-89c1-033a2c7d17bd/integrations/todoist.js:1
    renderTo moz-extension://c14f2050-21b4-4ea1-89c1-033a2c7d17bd/popupDlg/clockifyButton.js:1
    callback moz-extension://c14f2050-21b4-4ea1-89c1-033a2c7d17bd/popupDlg/clockifyButton.js:1
    c moz-extension://c14f2050-21b4-4ea1-89c1-033a2c7d17bd/popupDlg/clockifyDebounce.js:1
```

Browser: Firefox 110.0.1 64-bit for Ubuntu.

**Comment by pablodmv** [comment]
I have had the same issue in chrome Versión 110.0.5481.177 . I have clockify 2.9.3 chrome extension but isn't working with todoist.

**Comment by 7saraK** [comment]
Thank you both for the provided information. I have forwarded all this to our Devs, and will reach you back once I hear from them.

**Comment by 7saraK** [comment]
Hello both, @pablodmv and @kergma-lw, could you please advise if you can see the small timer button on the task list?

**Comment by JMSteinberg** [comment]
I also have the same situation that started a few weeks ago.  Did the steps above (firefox) and could not see the timer button on the todoist task list.  This is a great tool so I miss the functionality.

**Comment by 7saraK** [comment]
Thank you for letting me know this @JMSteinberg. I have confirmed this to the team, and will reach back with any updates I have. Wish you a nice weekend!

**Comment by 7saraK** [comment]
Hi againl, could you all reinstall the Clockify extension and double-check if the Timer button appeared on the task list?

**Comment by JMSteinberg** [comment]
Works!  Thanks!

**Comment by esalexreyes** [comment]
Seems to be broken again, probably due to some changes again on the Todoist front.

**Comment by JMSteinberg** [comment]
Has been working since March, but starting just the other day,  the Clockify extension on Firefox is not adding the button to track to the side of the task.  Still working in Chrome.

**Comment by Tyler-LeadRush** [comment]
Hey guys, I am experiencing the same issue with the Clockify extension not having the timer button next to the tasks in Todoist.

It's weird since it has worked for me for the longest time and suddenly stopped. I have tried clearing cookies, uninstalling/reinstalling the Clockify extension, and signing / out. At one point it worked for the night and after restarting my PC for the morning the issue persisted. 

Has anyone found a solution? @7saraK

**Comment by DavidGolic** [comment]
> Hey guys, I am experiencing the same issue with the Clockify extension not having the timer button next to the tasks in Todoist.
> 
> It's weird since it has worked for me for the longest time and suddenly stopped. I have tried clearing cookies, uninstalling/reinstalling the Clockify extension, and signing in / out. At one point it worked for the night and after restarting my PC for the morning the issue persisted.
> 
> Has anyone found a solution? @7saraK

Hello Tyler,

Please note that we have reported this to the Clockify Dev team and they are investigating the issue. 

You can always reach out to the Support team at support@clockify.me for more info.

Cheers,

**Comment by JMSteinberg** [comment]
just reinstalled the  Clockify extension on Firefox and it seems to now produce a timer button.  Thanks.
