### ISSUE TITLE
Clockify button not appearing in Pixie in Chrome browser

### ISSUE THREAD

**Issue by FakhriddinMakhmadiyorov** [clockify/browser-extension#301]
Clockify button is not appearing in Pixie:

<img width="1853" height="1015" alt="Image" src="https://github.com/user-attachments/assets/d2898939-1bfa-4dc6-83d1-2ee0c0876e75" />

- The button appears in Firefox
- There are no errors in browser log
- Pixie integration is enabled in the settings

The extension works for Firefox, but not for Chrome.

Chrome version: 143.0.7499.40
Clockify version: 2.11.36

**Comment by SupportTeamCAKEcom** [comment]
Hi there!

The issue has been fixed with the recently released 2.11.37 version of the extension.
In case you have any issues with the latest version, please feel free to contact us at support@clockify.me
Cheers!

**Comment by FakhriddinMakhmadiyorov** [comment]
@SupportTeamCAKEcom Hi,

Unfortunately, the button is still not appearing. I have cleared the browser cache and cookies, signed in again, and reinstalled the latest Chrome extension (v2.11.37). Despite this, I can see Clockify-related styles being loaded in the DOM.

**Comment by SupportTeamCAKEcom** [comment]
Hello!

Could you please reach out to us at support@clockify.me so we can troubleshoot your specific issue further? Thank you.
